title: 3DePlans - Learn House Design
short_title: 3DePlans
description: House Design for Contractors Designers and Home Owners.
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
  legal:
    output: true
    permalink: "/legal/:path/"
# tag_page_layout: tag_page
 # tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
include:
  - _legal
pages:
- legal/affiliate-disclosures.md
- legal/anti-spam-policy.md
- legal/cookie-policy.md
- legal/cookies-policy.md
- legal/dmca-digital-millennium-copyright-act.md
- legal/legal-disclaimer.md
- legal/linking-policy.md
- legal/privacy-policy.md
- legal/terms-and-conditions.md
- index.md